/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import avisos.Avisos;
import model.dao.CadastroUsuarioDao;
import model.dao.CpfDao;

/**
 *
 * @author Dih
 */
public class AEmail extends javax.swing.JPanel {

   private Avisos av = new Avisos();
   private CpfDao cpf1 = new CpfDao();
   private CadastroUsuarioDao dao = new CadastroUsuarioDao();
   Tela tela;
   
    public AEmail(Tela tela) {
        initComponents();
        this.tela=tela;
        alerta1.setVisible(false);
        alerta2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        email1 = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        alerta1 = new javax.swing.JLabel();
        alerta2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setBorder(null);
        email.setOpaque(false);
        add(email);
        email.setBounds(500, 240, 280, 30);

        email2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email2.setBorder(null);
        email2.setOpaque(false);
        add(email2);
        email2.setBounds(500, 400, 280, 20);

        email1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email1.setBorder(null);
        email1.setOpaque(false);
        add(email1);
        email1.setBounds(500, 320, 280, 30);

        confirmar.setBorder(null);
        confirmar.setContentAreaFilled(false);
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        add(confirmar);
        confirmar.setBounds(300, 570, 190, 30);

        cancelar.setBorder(null);
        cancelar.setContentAreaFilled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        add(cancelar);
        cancelar.setBounds(530, 570, 190, 30);

        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        add(voltar);
        voltar.setBounds(760, 570, 190, 30);

        sair.setBorder(null);
        sair.setContentAreaFilled(false);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        add(sair);
        sair.setBounds(30, 570, 190, 30);

        alerta1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        alerta1.setForeground(new java.awt.Color(255, 0, 0));
        alerta1.setText("Email incorreto");
        add(alerta1);
        alerta1.setBounds(580, 220, 100, 17);

        alerta2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        alerta2.setForeground(new java.awt.Color(255, 0, 0));
        alerta2.setText("Email não é igual");
        add(alerta2);
        alerta2.setBounds(460, 430, 110, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tela alterar email.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
       if(email.getText().equals(dao.retornar1())){
            if(email1.getText().equals(email2.getText())){
                dao.atualizaEmail(cpf1.retornar(), email1.getText());
                av.sucesso("Email atualizado");
                funcao1();
            }else{
                alerta2.setVisible(true);
                alerta1.setVisible(false);
            }
        }else{
            alerta1.setVisible(true);
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        funcao1();
    }//GEN-LAST:event_cancelarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        Configuracoes ini = new Configuracoes(this.tela);
        setVisible(false);
        tela.add(ini);
        ini.requestFocus();
    }//GEN-LAST:event_voltarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        if(av.sair()){
            if(cpf1.excluir()){
        Tela_Usuario cad = new Tela_Usuario(this.tela);
        setVisible(false);
        tela.add(cad);
        cad.requestFocus();
            }
        }
    }//GEN-LAST:event_sairActionPerformed

    public void funcao1(){
        email.setText("");
        email1.setText("");
       email2.setText("");
        alerta1.setVisible(false);
        alerta2.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alerta1;
    private javax.swing.JLabel alerta2;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JTextField email2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton sair;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
