
package view;

import avisos.Avisos;
import model.bean.CadastroCliente;
import model.dao.CadastroClienteDao;
import model.dao.CpfDao;

public class ClienteAtualizar extends javax.swing.JPanel {

    private CadastroCliente cliente;  
    private CadastroClienteDao dao = new CadastroClienteDao(); 
    private CpfDao cpf = new CpfDao();
    private Avisos avisos = new Avisos(); 
    private String cpfc;
    Tela tela;
    
    public ClienteAtualizar(Tela tela,String cpf) {
        initComponents();
        cpfc = cpf;
        this.tela = tela;
        setVisible(true);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sair = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        nome = new javax.swing.JTextField();
        cpft = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        ddd = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        celular = new javax.swing.JTextField();
        dataN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        sair.setBorder(null);
        sair.setContentAreaFilled(false);
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        add(sair);
        sair.setBounds(30, 560, 190, 40);

        atualizar.setBorder(null);
        atualizar.setContentAreaFilled(false);
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        add(atualizar);
        atualizar.setBounds(300, 560, 190, 40);

        cancelar.setBorder(null);
        cancelar.setContentAreaFilled(false);
        add(cancelar);
        cancelar.setBounds(530, 560, 190, 40);

        voltar.setBorder(null);
        voltar.setContentAreaFilled(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        add(voltar);
        voltar.setBounds(760, 560, 180, 40);

        nome.setEditable(false);
        nome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nome.setBorder(null);
        nome.setOpaque(false);
        add(nome);
        nome.setBounds(310, 220, 410, 30);

        cpft.setEditable(false);
        cpft.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cpft.setBorder(null);
        cpft.setOpaque(false);
        add(cpft);
        cpft.setBounds(310, 280, 210, 20);

        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setBorder(null);
        email.setOpaque(false);
        add(email);
        email.setBounds(310, 330, 400, 20);

        endereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        endereco.setBorder(null);
        endereco.setOpaque(false);
        add(endereco);
        endereco.setBounds(310, 380, 480, 20);

        ddd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ddd.setBorder(null);
        ddd.setOpaque(false);
        add(ddd);
        ddd.setBounds(310, 430, 50, 30);

        telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        telefone.setBorder(null);
        telefone.setOpaque(false);
        add(telefone);
        telefone.setBounds(390, 430, 200, 30);

        celular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        celular.setBorder(null);
        celular.setOpaque(false);
        add(celular);
        celular.setBounds(620, 430, 210, 30);

        dataN.setEditable(false);
        dataN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dataN.setBorder(null);
        dataN.setOpaque(false);
        add(dataN);
        dataN.setBounds(570, 280, 170, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tela Alterar real.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        InfoCliente ini = new InfoCliente(this.tela,cpfc);
        setVisible(false);
        tela.add(ini);
        ini.requestFocus();
    }//GEN-LAST:event_voltarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        cliente = new CadastroCliente(nome.getText(),cpft.getText(),dataN.getText(),email.getText(),endereco.getText(),Integer.parseInt(ddd.getText()),Long.parseLong(telefone.getText()),Long.parseLong(celular.getText()));
        if(dao.atualizar(cliente)){
            this.avisos.sucesso("Atualizado com sucesso");
        }else{
            System.out.println("ERRO");
        }
    }//GEN-LAST:event_atualizarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        if(this.cpf.excluir()){
        Tela_Usuario cad = new Tela_Usuario(this.tela);
        setVisible(false);
        tela.add(cad);
        cad.requestFocus();
        }else{ 
        }
    }//GEN-LAST:event_sairActionPerformed

public void mostrar(){
        if(dao.cliente(cpfc)){
            nome.setText(dao.getA());
            cpft.setText(dao.getB());
            dataN.setText(dao.getC());
            email.setText(dao.getD());
            endereco.setText(dao.getE());
            ddd.setText(String.valueOf(dao.getF()));
            telefone.setText(dao.getG());
            celular.setText(dao.getH());
        }else{
            System.err.println("Erro!!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField celular;
    private javax.swing.JTextField cpft;
    private javax.swing.JTextField dataN;
    private javax.swing.JTextField ddd;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nome;
    private javax.swing.JButton sair;
    private javax.swing.JTextField telefone;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
